clc; close all;

projectDir = fileparts(fileparts(mfilename('fullpath')));
addpath(genpath(fullfile(projectDir, 'lib')));
addpath(genpath(fullfile(projectDir, 'include')));

if ~ exist(fullfile(projectDir, 'tmp'), 'dir')
    mkdir(fullfile(projectDir, 'tmp'));
end

%% tests
fprintf('Start test of downloading AERONET level 1.5 AOD data\n');
download_AERONET_v3_AOD_web('Punta_Arenas_UMAG', ...
                             fullfile(projectDir, 'tmp', 'Punta_Arenas_UMAG_AOD15.txt'), ...
                             'productType', 'AOD15', ...
                             'starttime', datenum(2019, 1, 1), ...
                             'stoptime', datenum(2019, 1, 3));

fprintf('Start test of downloading AERONET level 1.5 SDA data\n');
download_AERONET_v3_AOD_web('Punta_Arenas_UMAG', ...
                             fullfile(projectDir, 'tmp', 'Punta_Arenas_UMAG_SDA15.txt'), ...
                             'productType', 'SDA15', ...
                             'starttime', datenum(2019, 1, 1), ...
                             'stoptime', datenum(2019, 1, 3));

fprintf('Start test of downloading AERONET level 1.5 INV size-distribution data\n');
download_AERONET_v3_INV_web('Punta_Arenas_UMAG', ...
                             fullfile(projectDir, 'tmp', 'Punta_Arenas_UMAG_SIZ.txt'), ...
                             'productType', 'SIZ', 'invType', 'ALM15', ...
                             'starttime', datenum(2019, 1, 1), ...
                             'stoptime', datenum(2019, 1, 3));